<?php

function voa_tealium_get_presets() {
    return(
array (
  0 => 
  array (
    0 => 'Entity',
    1 => 'Site name',
    2 => 'url',
    3 => 'Langauge',
    4 => 'Site ID',
    5 => 'Culture code',
    6 => 'Platform',
    7 => 'Property ID (for Tealium and Sitecatalyst)',
    8 => 'Language Service',
    9 => 'Short Language Service',
    10 => 'Short Platform',
  ),
  1 => 
  array (
    0 => 'VOA',
    1 => 'VOA Armenian Russia Watch Blog',
    2 => 'http://blogs.voanews.com/armenian/russia-watch/',
    3 => 'Armenian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '125',
    8 => 'VOA Armenian',
    9 => 'ARM',
    10 => 'B',
  ),
  2 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/armenian/armenia2013/',
    3 => 'Armenian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '124',
    8 => 'VOA Armenian',
    9 => 'ARM',
    10 => 'B',
  ),
  3 => 
  array (
    0 => 'VOA',
    1 => 'VOA Azerbaijani Audience Comments Blog',
    2 => 'http://blogs.voanews.com/azerbaijani/audience-comments/',
    3 => 'Azerbaijani',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '126',
    8 => 'VOA Azerbaijani',
    9 => 'AZ',
    10 => 'B',
  ),
  4 => 
  array (
    0 => 'VOA',
    1 => 'VOA Azerbajiani Diaspora Blog',
    2 => 'http://blogs.voanews.com/azerbaijani/azerbaijani-diaspora/',
    3 => 'Azerbaijani',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '127',
    8 => 'VOA Azerbaijani',
    9 => 'AZ',
    10 => 'B',
  ),
  5 => 
  array (
    0 => 'VOA',
    1 => 'VOA Azerbaijani Health and Medicine Blog',
    2 => 'http://blogs.voanews.com/azerbaijani/health-and-medicine/',
    3 => 'Azerbaijani',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '129',
    8 => 'VOA Azerbaijani',
    9 => 'AZ',
    10 => 'B',
  ),
  6 => 
  array (
    0 => 'VOA',
    1 => 'VOA Azerbajiani Washington Pulse Blog',
    2 => 'http://blogs.voanews.com/azerbaijani/washington-pulse/',
    3 => 'Azerbaijani',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '131',
    8 => 'VOA Azerbaijani',
    9 => 'AZ',
    10 => 'B',
  ),
  7 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/azerbaijani/ferhadoglu/',
    3 => 'Azerbaijani',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '128',
    8 => 'VOA Azerbaijani',
    9 => 'AZ',
    10 => 'B',
  ),
  8 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/azerbaijani/sports/',
    3 => 'Azerbaijani',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '130',
    8 => 'VOA Azerbaijani',
    9 => 'AZ',
    10 => 'B',
  ),
  9 => 
  array (
    0 => 'VOA',
    1 => 'VOA African Music Treasures Blog',
    2 => 'http://blogs.voanews.com/african-music-treasures/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '123',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  10 => 
  array (
    0 => 'VOA',
    1 => 'VOA Digital Frontiers Blog',
    2 => 'http://blogs.voanews.com/digital-frontiers/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '134',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  11 => 
  array (
    0 => 'VOA',
    1 => 'VOA English Inside Iran Blog',
    2 => 'http://blogs.voanews.com/inside-iran/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '142',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  12 => 
  array (
    0 => 'VOA',
    1 => 'VOA English Middle East Voices',
    2 => 'middleeastvoices.voanews.com',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '289',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  13 => 
  array (
    0 => 'VOA',
    1 => 'VOA English Russia Watch Blog',
    2 => 'http://blogs.voanews.com/russia-watch/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '154',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  14 => 
  array (
    0 => 'VOA',
    1 => 'VOA English Science World Blog',
    2 => 'http://blogs.voanews.com/science-world/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '169',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  15 => 
  array (
    0 => 'VOA',
    1 => 'VOA English Sonny Side of Sports Blog',
    2 => 'http://blogs.voanews.com/sonny/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '170',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  16 => 
  array (
    0 => 'VOA',
    1 => 'VOA English State of Affairs Blog',
    2 => 'http://blogs.voanews.com/state-department-news/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '173',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  17 => 
  array (
    0 => 'VOA',
    1 => 'VOA English Student Union Blog',
    2 => 'http://blogs.voanews.com/student-union/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '174',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  18 => 
  array (
    0 => 'VOA',
    1 => 'VOA English USA Politics Blog',
    2 => 'http://blogs.voanews.com/usa-politics/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '187',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  19 => 
  array (
    0 => 'VOA',
    1 => 'VOA Music Blog',
    2 => 'http://blogs.voanews.com/music/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '153',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  20 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '122',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  21 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/china-wangre/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '132',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  22 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/jazz-beat/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '143',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  23 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/living-green/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '152',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  24 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/tedlandphairsamerica/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '175',
    8 => 'VOA English',
    9 => 'EN',
    10 => 'B',
  ),
  25 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/khmer-english/crossroads/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '144',
    8 => 'VOA English',
    9 => 'KHM',
    10 => 'B',
  ),
  26 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/khmer-english/musings/',
    3 => 'English',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '145',
    8 => 'VOA English',
    9 => 'KHM',
    10 => 'B',
  ),
  27 => 
  array (
    0 => 'VOA',
    1 => 'VOA Georgian American Blog',
    2 => 'http://blogs.voanews.com/georgian/georgianamerica/',
    3 => 'Georgian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '136',
    8 => 'VOA Georgian',
    9 => 'GEO',
    10 => 'B',
  ),
  28 => 
  array (
    0 => 'VOA',
    1 => 'VOA Georgian Russia Watch Blog',
    2 => 'http://blogs.voanews.com/georgian/russia-watch/',
    3 => 'Georgian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '139',
    8 => 'VOA Georgian',
    9 => 'GEO',
    10 => 'B',
  ),
  29 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/georgian/forum/',
    3 => 'Georgian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '135',
    8 => 'VOA Georgian',
    9 => 'GEO',
    10 => 'B',
  ),
  30 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/georgian/hot-zone/',
    3 => 'Georgian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '137',
    8 => 'VOA Georgian',
    9 => 'GEO',
    10 => 'B',
  ),
  31 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/georgian/myamerica/',
    3 => 'Georgian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '138',
    8 => 'VOA Georgian',
    9 => 'GEO',
    10 => 'B',
  ),
  32 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/indonesian/kontes-ngeblog-voa/',
    3 => 'Indonesian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '140',
    8 => 'VOA Indonesian',
    9 => 'IND',
    10 => 'B',
  ),
  33 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/indonesian/pojokan-dc/',
    3 => 'Indonesian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '141',
    8 => 'VOA Indonesian',
    9 => 'IND',
    10 => 'B',
  ),
  34 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/korean/photos/',
    3 => 'Korean',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '146',
    8 => 'VOA Korean',
    9 => 'KOR',
    10 => 'B',
  ),
  35 => 
  array (
    0 => 'VOA',
    1 => 'VOA Kurdish Balensalih Blog',
    2 => 'http://blogs.voanews.com/kurdish/balensalih/',
    3 => 'Kurdi',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '149',
    8 => 'VOA Kurdi',
    9 => 'KRDS',
    10 => 'B',
  ),
  36 => 
  array (
    0 => 'VOA',
    1 => 'VOA Kurdish Karwanseray Blog',
    2 => 'http://blogs.voanews.com/kurdish/karwanseray/',
    3 => 'Kurdi',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '150',
    8 => 'VOA Kurdi',
    9 => 'KRDS',
    10 => 'B',
  ),
  37 => 
  array (
    0 => 'VOA',
    1 => 'VOA Kurdi Washingtonname Blog',
    2 => 'http://blogs.voanews.com/kurdi/washingtonname/',
    3 => 'Kurdi',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '147',
    8 => 'VOA Kurdi',
    9 => 'KRDI',
    10 => 'B',
  ),
  38 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/kurdi/zimanujiyan/',
    3 => 'Kurdi',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '148',
    8 => 'VOA Kurdi',
    9 => 'KRDI',
    10 => 'B',
  ),
  39 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/kurdish/kermanshan/',
    3 => 'Kurdi',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '151',
    8 => 'VOA Kurdi',
    9 => 'KRDS',
    10 => 'B',
  ),
  40 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/chinese/news-in-brief/',
    3 => 'Mandarin',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '133',
    8 => 'VOA Mandarin',
    9 => 'MAN',
    10 => 'B',
  ),
  41 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian Election Monitor Blog',
    2 => 'http://blogs.voanews.com/russian/election-monitor/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '159',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  42 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian Ganapolsky America Blog',
    2 => 'http://blogs.voanews.com/russian/ganapolsky-america/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '160',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  43 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian Grigoryev Blog',
    2 => 'http://blogs.voanews.com/russian/grigoryev/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '161',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  44 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian New Eurasia Blog',
    2 => 'http://blogs.voanews.com/russian/new-eurasia/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '162',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  45 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian Photo Blog',
    2 => 'http://blogs.voanews.com/russian/photos/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '163',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  46 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian Press Blog',
    2 => 'http://blogs.voanews.com/russian/press/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '165',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  47 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian Russia Watch',
    2 => 'http://blogs.voanews.com/russian/russia-watch/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '166',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  48 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian Students Blog',
    2 => 'http://blogs.voanews.com/russian/students/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '167',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  49 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian US-Russia Blog',
    2 => 'http://blogs.voanews.com/russian/us-russia/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '168',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  50 => 
  array (
    0 => 'VOA',
    1 => 'VOA Russian Washington Diary Blog',
    2 => 'http://blogs.voanews.com/russian/donald-jensen-washington-diary/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '157',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  51 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/russian/developing-story/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '155',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  52 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/russian/dmitriev-america/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '156',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  53 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/russian/economy/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '158',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  54 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/russian/pop-culture/',
    3 => 'Russian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '164',
    8 => 'VOA Russian',
    9 => 'RU',
    10 => 'B',
  ),
  55 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/spanish/comite-de-estudiantes/',
    3 => 'Spanish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '171',
    8 => 'VOA Spanish',
    9 => 'SPA',
    10 => 'B',
  ),
  56 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/spanish/voz-de-america/',
    3 => 'Spanish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '172',
    8 => 'VOA Spanish',
    9 => 'SPA',
    10 => 'B',
  ),
  57 => 
  array (
    0 => 'VOA',
    1 => 'Turkish Campus Diary',
    2 => 'http://blogs.voanews.com/turkish/kampus-gunlugu/',
    3 => 'Turkish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '178',
    8 => 'VOA Turkish',
    9 => 'TURK',
    10 => 'B',
  ),
  58 => 
  array (
    0 => 'VOA',
    1 => 'VOA Turkish Gokkusagi Blog',
    2 => 'http://blogs.voanews.com/turkish/gokkusagi/',
    3 => 'Turkish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '176',
    8 => 'VOA Turkish',
    9 => 'TURK',
    10 => 'B',
  ),
  59 => 
  array (
    0 => 'VOA',
    1 => 'VOA Turkish Motosikletli Kiz Blog',
    2 => 'http://blogs.voanews.com/turkish/selin/',
    3 => 'Turkish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '181',
    8 => 'VOA Turkish',
    9 => 'TURK',
    10 => 'B',
  ),
  60 => 
  array (
    0 => 'VOA',
    1 => 'VOA Turkish Technology Blog',
    2 => 'http://blogs.voanews.com/turkish/teknoloji/',
    3 => 'Turkish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '182',
    8 => 'VOA Turkish',
    9 => 'TURK',
    10 => 'B',
  ),
  61 => 
  array (
    0 => 'VOA',
    1 => 'VOA Turkish Yeni Economi Blog',
    2 => 'http://blogs.voanews.com/turkish/melekcaglar/',
    3 => 'Turkish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '179',
    8 => 'VOA Turkish',
    9 => 'TURK',
    10 => 'B',
  ),
  62 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/turkish/hayatimizegitim/',
    3 => 'Turkish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '177',
    8 => 'VOA Turkish',
    9 => 'TURK',
    10 => 'B',
  ),
  63 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/turkish/milhan/',
    3 => 'Turkish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '180',
    8 => 'VOA Turkish',
    9 => 'TURK',
    10 => 'B',
  ),
  64 => 
  array (
    0 => 'VOA',
    1 => '',
    2 => 'http://blogs.voanews.com/turkish/washingtonnotlari/',
    3 => 'Turkish',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '183',
    8 => 'VOA Turkish',
    9 => 'TURK',
    10 => 'B',
  ),
  65 => 
  array (
    0 => 'VOA',
    1 => 'VOA Ukrainian Economy Blog',
    2 => 'http://blogs.voanews.com/ukrainian/economy/',
    3 => 'Ukrainian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '184',
    8 => 'VOA Ukrainian',
    9 => 'UKR',
    10 => 'B',
  ),
  66 => 
  array (
    0 => 'VOA',
    1 => 'VOA Ukrainian Election Monitor Blog',
    2 => 'http://blogs.voanews.com/ukrainian/election-monitor/',
    3 => 'Ukrainian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '185',
    8 => 'VOA Ukrainian',
    9 => 'UKR',
    10 => 'B',
  ),
  67 => 
  array (
    0 => 'VOA',
    1 => 'VOA Ukrainian Kyiv Report Blog',
    2 => 'http://blogs.voanews.com/ukrainian/kyivreport/',
    3 => 'Ukrainian',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '186',
    8 => 'VOA Ukrainian',
    9 => 'UKR',
    10 => 'B',
  ),
  68 => 
  array (
    0 => 'VOA',
    1 => 'VOA Uzbek Tadbirkorlar Fabrikasi Blog',
    2 => 'http://blogs.voanews.com/uzbek/kichikbiz/',
    3 => 'Uzbek',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '189',
    8 => 'VOA Uzbek',
    9 => 'UZB',
    10 => 'B',
  ),
  69 => 
  array (
    0 => 'VOA',
    1 => 'VOA Uzbek Inter-GAP Blog',
    2 => 'http://blogs.voanews.com/uzbek/inter-gap/',
    3 => 'Uzbek',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '188',
    8 => 'VOA Uzbek',
    9 => 'UZB',
    10 => 'B',
  ),
  70 => 
  array (
    0 => 'VOA',
    1 => 'VOA Uzbek Vatan Manzaralari Blog',
    2 => 'http://blogs.voanews.com/uzbek/vatan-manzaralari/',
    3 => 'Uzbek',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '191',
    8 => 'VOA Uzbek',
    9 => 'UZB',
    10 => 'B',
  ),
  71 => 
  array (
    0 => 'VOA',
    1 => 'VOA Uzbek Talabalar Shaharchasi Blog',
    2 => 'http://blogs.voanews.com/uzbek/talabalar-shaharchasi/',
    3 => 'Uzbek',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '190',
    8 => 'VOA Uzbek',
    9 => 'UZB',
    10 => 'B',
  ),
  72 => 
  array (
    0 => 'VOA',
    1 => 'VOA Uzbek Yuridik-Klinika Blog',
    2 => 'http://blogs.voanews.com/uzbek/yuridik-klinika/',
    3 => 'Uzbek',
    4 => '',
    5 => '',
    6 => 'Blog',
    7 => '192',
    8 => 'VOA Uzbek',
    9 => 'UZB',
    10 => 'B',
  ),
)
    );
}
